name: feasy_socket
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  { shelf: ^1.4.0, shelf_web_socket: ^1.0.3, web_socket_channel: ^2.3.0 }
